apiVersion: v1
kind: Pod
metadata:
  name: cve-pod
  labels:
    app: nginx
spec:
  restartPolicy: Always
  containers:
  - name: nginx
    image: mambroziak/cve-2013-2028
    # Just spin & wait forever
    command: [ "sh", "-c", "service nginx start; while true; do sleep 30; done;" ]
    imagePullPolicy: Always